#! /bin/sh

set -euo pipefail

install-system-deps() {
    sudo apt install rustc poetry
}

install-metamath() {
    (cd mm0/mm0-c; ./make.sh)
    (cd mm0/mm0-rs; cargo build --release)
}

install-maude() {
    cp maude/maude.linux64 maude/maude
}

install-python-deps() {
    poetry install --no-root
}

install-system-deps
install-metamath
install-maude
install-python-deps
