#! /usr/bin/env bash

set -euo pipefail
export PATH=/home/tacas23/.local/bin:$PATH

install-system-deps() {
    sudo apt-get --yes update
    sudo apt --yes install cargo rustc
    pip3 install poetry
}

install-metamath() {
    (cd mm0/mm0-c; ./make.sh)
    (cd mm0/mm0-rs; cargo build --release)
}

install-maude() {
    cp maude/maude.linux64 maude/maude
}

install-python-deps() {
    poetry install --no-root
}

install-system-deps
install-metamath
install-maude
install-python-deps
